language: php

sudo: required

dist: xenial

branches:
    only:
        - master
        - /^\d+\.\d+$/
env:
    global:
        - THRIFT_VERSION=0.9.2

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: SYMFONY_VERSION=2.3.*
        - php: 5.5
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*
        - php: 7.1
          env: SYMFONY_VERSION=3.1.*
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/thrift

before_install:
    - /bin/bash $TRAVIS_BUILD_DIR/.travis/bin/install-thrift-compiler
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then (php -m | grep thrift) || true; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "5.6" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini || true; fi
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer require "apache/thrift:${THRIFT_VERSION}"
    - if [ "$TRAVIS_PHP_VERSION" != "5.4" ]; then composer require "symfony/cache:^3.1" "ocramius/proxy-manager:^1.0" "guzzlehttp/promises:^1.1"; fi

install:
    - composer update --prefer-dist --no-interaction

script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then bin/phpunit -d xdebug.max_nesting_level=1000 --debug --coverage-clover=coverage.clover; else bin/phpunit --debug; fi

#after_script:
#    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
